export const regions = {
  SP: "São Paulo",
  MG: "Minas Gerais",
  RJ: "Rio de Janeiro",
  BA: "Bahia",
  RS: "Rio Grande do Sul",
  PR: "Paraná",
  PE: "Pernambuco",
  CE: "Ceará",
  MA: "Maranhão",
  SC: "Santa Catarina",
  GO: "Goiás",
  AM: "Amazonas",
  ES: "Espírito Santo",
  PB: "Paraíba",
  RN: "Rio Grande do Norte",
  AL: "Alagoas",
  MT: "Mato Grosso",
  PI: "Piauí",
  DF: "Distrito Federal",
  MS: "Mato Grosso do Sul",
  SE: "Sergipe",
  RO: "Rondônia",
  AC: "Acre",
  AP: "Amapá",
  RR: "Roraima",
  TO: "Tocantins"
};
